vse: &vse
  docker:
    - image: circleci/node:8.11.3

version: 2.1
jobs:
#  build:
#    <<: *vse
#    steps:
#      - checkout
#      - run: npm install
#      - run: npm run test
#      - run: npm run build
#      - persist_to_workspace:
#          root: .
#          paths:
#            - .

  deploy:
    description: "Deploy app to AWS"
    <<: *vse
    docker:
      - image: circleci/python:3.6.4
    working_directory: ~/.circleci
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
      - run:
          name: "Install ansible ..."
          command: pip install ansible boto boto3
      - add_ssh_keys:
          fingerprints:
            - "02:f5:53:fd:1c:9b:e7:6d:bf:d5:c3:04:66:87:26:5d:30:49:15:80"
      - run:
          name: "Set to deploy directory"
          command: cd deploy/
      - run:
          name: "Run Ansible deploy script"
          command: ansible-playbook deploy/aws_deploy.yml \
            --extra-vars "access_key=$aws_access_key secret_key=$aws_secret_key session_token=$aws_session_token" \
            --ssh-extra-args "-o StrictHostKeyChecking=no"

workflows:
  version: 2.1
  build-and-deploy:
    jobs:
#      - build
      - deploy
#          requires:
#            - build
#          filters:
#            branches:
#              only: master
