vse: &vse
  docker:
    - image: circleci/node:8.11.3

version: 2.1
jobs:
  build:
    <<: *vse
    steps:
      - checkout
      - run: npm install
      - run: npm run test
      - run: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - .

  deploy:
    description: "Execute ansible-lint command"
    <<: *vse
    docker:
      - image: circleci/python:3.6.4
    context: 4it572_sem # name of deploy context in CircleCI
    steps:
      - attach_workspace:
          at: .
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
      - run:
          name: "Install ansible lint"
          command: pip install ansible boto boto3
      - run:
          name: "Run Ansible deploy script"
          command: ansible-playbook ../.ansible/aws_deploy.yml \
            --extra-vars "access_key=$aws_access_key secret_key=$aws_secret_key security_token=$aws_security_token"


#      - run: ansible-playbook ../.ansible/aws_deploy.yaml

workflows:
  version: 2.1
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
